export const SAVE_USER = 'SAVE_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const VIEW_THIS_USER = 'VIEW_THIS_USER';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const SAVE_SEARCH_STATE = 'SAVE_SEARCH_STATE';
export const CLEAR_FLASH_MESSAGE = 'CLEAR_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SAVE_PROFILE_VIEW_STATE = 'SAVE_PROFILE_VIEW_STATE';
