export const SAVE_USER = 'SAVE_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const SAVE_SEARCH_STATE = 'SAVE_SEARCH_STATE';
export const SAVE_PROFILE_STATS = 'SAVE_PROFILE_STATS';
export const CLEAR_FLASH_MESSAGE = 'CLEAR_FLASH_MESSAGE';
export const SAVE_PREFERENCES_VIEW_STATE = 'SAVE_PREFERENCES_VIEW_STATE';
